language: java

sudo: false

jdk:
  - openjdk10

install: true

before_script:
  - make prepare

script: make build_core

after_success:
  - coveralls

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'
    
